version: '2'

services:
  auth:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules/

    # Expose ports [HOST:CONTAINER}
    ports:
      - "4040:4040"

    # Set environment variables from this file
    env_file:
      - .env

    # Overwrite any env var defined in .env file (if required)
    environment:
      - MONGO_HOST=mongodb://mongo/apiAuth
      - DEBUG=apiAuth:*

    links:
      - mongo

  mongo:
    image: "mongo:3.4"
    ports:
      - "27017:27017"
